export const locationData: { [key: string]: { [key: string]: string[] } } = {
  Maharashtra: {
    Ahmednagar: ["Ahmednagar City", "Sangamner", "Kopargaon", "Shrirampur", "Rahuri"],
    Akola: ["Akola City", "Akot", "Balapur", "Patur", "Telhara"],
    Amravati: ["Amravati City", "Achalpur", "Anjangaon Surji", "Daryapur", "Warud"],
    Aurangabad: ["Aurangabad City", "Paithan", "Gangapur", "Vaijapur", "Kannad"],
    Beed: ["Beed City", "Ambejogai", "Majalgaon", "Parli", "Georai"],
    Bhandara: ["Bhandara City", "Tumsar", "Pauni", "Sakoli", "Lakhani"],
    Buldhana: ["Buldhana City", "Chikhli", "Mehekar", "Malkapur", "Shegaon"],
    Chandrapur: ["Chandrapur City", "Ballarpur", "Warora", "Bhadravati", "Rajura"],
    Dhule: ["Dhule City", "Shirpur", "Sakri", "Sindkhede", "Dondaicha"],
    Gadchiroli: ["Gadchiroli City", "Aheri", "Armori", "Chamorshi", "Desaiganj"],
    Gondia: ["Gondia City", "Tirora", "Arjuni Morgaon", "Amgaon", "Deori"],
    Hingoli: ["Hingoli City", "Basmath", "Kalamnuri", "Sengao", "Aundha Nagnath"],
    Jalgaon: ["Jalgaon City", "Bhusawal", "Amalner", "Chalisgaon", "Pachora"],
    Jalna: ["Jalna City", "Ambad", "Partur", "Bhokardan", "Jafrabad"],
    Kolhapur: ["Kolhapur City", "Ichalkaranji", "Jaysingpur", "Radhanagari", "Kagal"],
    Latur: ["Latur City", "Udgir", "Ahmedpur", "Nilanga", "Ausa"],
    Mumbai: ["Colaba", "Dadar", "Andheri", "Bandra", "Borivali"],
    Nagpur: ["Nagpur City", "Kamptee", "Umred", "Katol", "Ramtek"],
    Nanded: ["Nanded City", "Deglur", "Loha", "Hadgaon", "Mukhed"],
    Nandurbar: ["Nandurbar City", "Shahada", "Taloda", "Akkalkuwa", "Nawapur"],
    Nashik: ["Nashik City", "Malegaon", "Manmad", "Yeola", "Sinnar", "Indira Nagar"],
    Osmanabad: ["Osmanabad City", "Tuljapur", "Omerga", "Kalamb", "Paranda"],
    Palghar: ["Palghar City", "Vasai-Virar", "Dahanu", "Boisar", "Jawhar"],
    Parbhani: ["Parbhani City", "Selu", "Jintur", "Gangakhed", "Purna"],
    Pune: ["Pune City", "Pimpri-Chinchwad", "Baramati", "Lonavala", "Junnar", "Shivajinagar"],
    Raigad: ["Panvel", "Alibaug", "Mahad", "Karjat", "Roha"],
    Ratnagiri: ["Ratnagiri City", "Chiplun", "Khed", "Guhagar", "Lanja"],
    Sangli: ["Sangli City", "Miraj", "Islampur", "Vita", "Tasgaon"],
    Satara: ["Satara City", "Karad", "Phaltan", "Wai", "Koregaon"],
    Sindhudurg: ["Sawantwadi", "Malvan", "Kankavli", "Kudal", "Vengurla"],
    Solapur: ["Solapur City", "Barshi", "Pandharpur", "Akluj", "Sangola"],
    Thane: ["Thane City", "Kalyan-Dombivli", "Navi Mumbai", "Ulhasnagar", "Bhiwandi", "Mira-Bhayandar"],
    Wardha: ["Wardha City", "Hinganghat", "Arvi", "Pulgaon", "Wardha"],
    Washim: ["Washim City", "Risod", "Karanja", "Mangrulpir", "Malegaon"],
    Yavatmal: ["Yavatmal City", "Pusad", "Digras", "Wani", "Umarkhed"]
  },
  Delhi: {
    "Central Delhi": ["Connaught Place", "Karol Bagh", "Pahar Ganj", "Chandni Chowk", "Daryaganj"],
    "New Delhi": ["Chanakyapuri", "Lodhi Colony", "Gole Market", "Sarojini Nagar", "Laxmibai Nagar"],
    "South Delhi": ["Saket", "Hauz Khas", "Mehrauli", "Greater Kailash", "Malviya Nagar"],
    "North Delhi": ["Civil Lines", "Model Town", "Saraswati Vihar", "Rohini", "Kamla Nagar"],
    "East Delhi": ["Preet Vihar", "Mayur Vihar", "Laxmi Nagar", "Shahdara", "Gandhi Nagar"],
    "West Delhi": ["Rajouri Garden", "Punjabi Bagh", "Janakpuri", "Vikaspuri", "Dwarka"],
    "North East Delhi": ["Seelampur", "Shahdara", "Yamuna Vihar", "Nand Nagri", "Dilshad Garden"],
    "North West Delhi": ["Rohini", "Pitampura", "Saraswati Vihar", "Adarsh Nagar", "Kanjhawala"],
    "South East Delhi": ["Okhla", "Kalkaji", "Lajpat Nagar", "Defence Colony", "Nehru Place"],
    "South West Delhi": ["Dwarka", "Vasant Kunj", "Najafgarh", "Delhi Cantt", "R.K. Puram"]
  },
  Karnataka: {
    "Bangalore Urban": ["Indiranagar", "Koramangala", "Jayanagar", "Whitefield", "Electronic City", "M.G. Road"],
    "Bangalore Rural": ["Devanahalli", "Doddaballapur", "Hosakote", "Nelamangala", "Magadi"],
    Mysore: ["Mysore City", "Nanjangud", "Hunsur", "T. Narasipura", "K.R. Nagar"],
    Belgaum: ["Belgaum City", "Chikodi", "Gokak", "Athani", "Bailhongal"],
    Gulbarga: ["Gulbarga City", "Afzalpur", "Aland", "Chincholi", "Sedam"],
    Mangalore: ["Mangalore City", "Ullal", "Mulki", "Bantwal", "Puttur"],
    Hubli: ["Hubli-Dharwad", "Kalghatgi", "Navalgund", "Kundgol", "Alnavar"],
    Dharwad: ["Dharwad City", "Hubli", "Kalghatgi", "Navalgund", "Kundgol"]
  },
  Haryana: {
    Gurgaon: ["Gurgaon City", "Sohna", "Pataudi", "Manesar", "Farrukhnagar"],
    Faridabad: ["Faridabad City", "Ballabgarh", "Tigaon", "Faridabad", "Sector 15"],
    Panipat: ["Panipat City", "Samalkha", "Israna", "Madlauda", "Bapoli"],
    Ambala: ["Ambala City", "Ambala Cantt", "Naraingarh", "Shahzadpur", "Saha"],
    Rohtak: ["Rohtak City", "Meham", "Sampla", "Kalanaur", "Lakhman Majra"]
  },
  Telangana: {
    Hyderabad: ["Hyderabad City", "Secunderabad", "Gachibowli", "Madhapur", "Jubilee Hills", "Banjara Hills"],
    Rangareddy: ["Cyberabad", "Kukatpally", "LB Nagar", "Rajendranagar", "Quthbullapur"],
    Warangal: ["Warangal City", "Hanamkonda", "Kazipet", "Jangaon", "Mahabubabad"],
    Nizamabad: ["Nizamabad City", "Armoor", "Bodhan", "Kamareddy", "Banswada"],
    Karimnagar: ["Karimnagar City", "Jagtial", "Sircilla", "Koratla", "Metpally"]
  }
};

export const governmentHospitals = [
    {
        id: "gov-1",
        name: "AIIMS Delhi",
        specialization: "Multi-specialty",
        hospitalName: "All India Institute of Medical Sciences",
        hospitalAddress: "Ansari Nagar, New Delhi - 110029",
        lat: 28.5672,
        lng: 77.2100,
        state: "Delhi",
        district: "South Delhi",
        village: "Saket",
        isVerified: true,
        type: "Government",
        consultationFee: 0,
        contact: "011-26588500",
        bio: "India's premier public medical research university and hospital providing accessible high-quality tertiary care.",
        notableDoctors: [
            { name: "Dr. Randeep Guleria", role: "Pulmonologist" },
            { name: "Dr. Aarti Vij", role: "Hospital Administration" },
            { name: "Dr. Nikhil Tandon", role: "Endocrinology" }
        ]
    },
    {
        id: "gov-2",
        name: "Safdarjung Hospital",
        specialization: "Multi-specialty",
        hospitalName: "Vardhman Mahavir Medical College & Safdarjung Hospital",
        hospitalAddress: "Ansari Nagar East, New Delhi - 110029",
        lat: 28.5685,
        lng: 77.2065,
        state: "Delhi",
        district: "South Delhi",
        village: "Hauz Khas",
        isVerified: true,
        type: "Government",
        consultationFee: 0,
        contact: "011-26730000",
        bio: "One of the largest government hospitals in India, offering specialized departments and a 2,000+ bed facility.",
        notableDoctors: [
            { name: "Dr. S.V. Arya", role: "Medical Superintendent" },
            { name: "Dr. Balvinder Singh", role: "Orthopedics" }
        ]
    },
    {
        id: "gov-3",
        name: "Ram Manohar Lohia Hospital",
        specialization: "Multi-specialty",
        hospitalName: "Dr. Ram Manohar Lohia Hospital",
        hospitalAddress: "Baba Kharak Singh Marg, New Delhi - 110001",
        lat: 28.6256,
        lng: 77.2024,
        state: "Delhi",
        district: "Central Delhi",
        village: "Connaught Place",
        isVerified: true,
        type: "Government",
        consultationFee: 0,
        contact: "011-23365525",
        bio: "A renowned central government hospital providing emergency services and specialized care in the heart of Delhi.",
        notableDoctors: [
            { name: "Dr. Nandini Duggal", role: "Microbiology" },
            { name: "Dr. Ajay Shukla", role: "Surgery" }
        ]
    },
    {
        id: "gov-4",
        name: "Lok Nayak Hospital",
        specialization: "Multi-specialty",
        hospitalName: "Lok Nayak Jai Prakash Narayan Hospital",
        hospitalAddress: "Jawaharlal Nehru Marg, New Delhi - 110002",
        lat: 28.6360,
        lng: 77.2340,
        state: "Delhi",
        district: "Central Delhi",
        village: "Chandni Chowk",
        isVerified: true,
        type: "Government",
        consultationFee: 0,
        contact: "011-23236000",
        bio: "A major tertiary care hospital under the Delhi Government, catering to a vast population with state-of-the-art facilities.",
        notableDoctors: [
            { name: "Dr. Suresh Kumar", role: "Internal Medicine" },
            { name: "Dr. B.L. Sherwal", role: "Administration" }
        ]
    },
    {
        id: "pvt-6",
        name: "Max Super Speciality Saket",
        specialization: "Multi-specialty",
        hospitalName: "Max Super Speciality Hospital Saket",
        hospitalAddress: "1, 2, Press Enclave Road, Saket, New Delhi - 110017",
        lat: 28.5283,
        lng: 77.2106,
        state: "Delhi",
        district: "South Delhi",
        village: "Saket",
        isVerified: true,
        type: "Government",
        consultationFee: 800,
        contact: "011-26515050",
        bio: "A leading private multispecialty hospital known for its expertise in cardiac sciences and oncology.",
        notableDoctors: [
            { name: "Dr. Balbir Singh", role: "Cardiology" },
            { name: "Dr. Harit Chaturvedi", role: "Oncology" }
        ]
    },
    {
        id: "pvt-7",
        name: "Manipal Hospital Bangalore",
        specialization: "Multi-specialty",
        hospitalName: "Manipal Hospitals Old Airport Road",
        hospitalAddress: "98, HAL Old Airport Rd, Bengaluru - 560017",
        lat: 12.9592,
        lng: 77.6468,
        state: "Karnataka",
        district: "Bangalore Urban",
        village: "Indiranagar",
        isVerified: true,
        type: "Government",
        consultationFee: 950,
        contact: "080-22221111",
        bio: "A flagship tertiary care facility offering patient-centric healthcare and advanced diagnostic services.",
        notableDoctors: [
            { name: "Dr. Sudarshan Ballal", role: "Nephrology" },
            { name: "Dr. H. Sudarshan", role: "Public Health" }
        ]
    },
    {
        id: "pvt-8",
        name: "Lilavati Hospital Mumbai",
        specialization: "Multi-specialty",
        hospitalName: "Lilavati Hospital and Research Centre",
        hospitalAddress: "A-791, Bandra Reclamation, Bandra West, Mumbai - 400050",
        lat: 19.0509,
        lng: 72.8294,
        state: "Maharashtra",
        district: "Mumbai",
        village: "Bandra",
        isVerified: true,
        type: "Government",
        consultationFee: 1200,
        contact: "022-26751000",
        bio: "A premier multi-specialty tertiary care hospital in Mumbai providing compassionate care with advanced technology.",
        notableDoctors: [
            { name: "Dr. V. Ravishankar", role: "CEO" },
            { name: "Dr. Shashank Joshi", role: "Endocrinology" }
        ]
    },
    {
        id: "pvt-9",
        name: "Tata Memorial Hospital",
        specialization: "Oncology",
        hospitalName: "Tata Memorial Centre",
        hospitalAddress: "Dr Ernest Borges Road, Parel, Mumbai - 400012",
        lat: 19.0048,
        lng: 72.8437,
        state: "Maharashtra",
        district: "Mumbai",
        village: "Dadar",
        isVerified: true,
        type: "Government",
        consultationFee: 0,
        contact: "022-24177000",
        bio: "The premier cancer center of India, specialized in cancer treatment, research, and education.",
        notableDoctors: [
            { name: "Dr. R.A. Badwe", role: "Surgical Oncology" },
            { name: "Dr. Pankaj Chaturvedi", role: "Head & Neck Surgery" }
        ]
    },
    {
        id: "pvt-10",
        name: "Sir Ganga Ram Hospital",
        specialization: "Multi-specialty",
        hospitalName: "Sir Ganga Ram Hospital",
        hospitalAddress: "Rajinder Nagar, New Delhi - 110060",
        lat: 28.6369,
        lng: 77.1895,
        state: "Delhi",
        district: "Central Delhi",
        village: "Connaught Place",
        isVerified: true,
        type: "Government",
        consultationFee: 1000,
        contact: "011-25750000",
        bio: "A multi-speciality state-of-the-art hospital known for providing comprehensive healthcare services in Delhi.",
        notableDoctors: [
            { name: "Dr. D.S. Rana", role: "Nephrology" },
            { name: "Dr. S.P. Byotra", role: "Medicine" }
        ]
    },
    {
        id: "pvt-11",
        name: "Ruby Hall Clinic Pune",
        specialization: "Multi-specialty",
        hospitalName: "Ruby Hall Clinic",
        hospitalAddress: "40, Sassoon Road, Pune - 411001",
        lat: 18.5275,
        lng: 73.8765,
        state: "Maharashtra",
        district: "Pune",
        village: "Shivajinagar",
        isVerified: true,
        type: "Government",
        consultationFee: 700,
        contact: "020-66455100",
        bio: "Pune's first externally accredited multi-specialty hospital providing high-quality healthcare for over 50 years.",
        notableDoctors: [
            { name: "Dr. Purvez Grant", role: "Cardiology" },
            { name: "Dr. Sanjay Deshmukh", role: "Surgery" }
        ]
    },
    {
        id: "pvt-12",
        name: "Amrita Hospital Faridabad",
        specialization: "Multi-specialty",
        hospitalName: "Amrita Hospital",
        hospitalAddress: "Sector 88, Mata Amritanandamayi Marg, Faridabad - 121002",
        lat: 28.3669,
        lng: 77.2928,
        state: "Haryana",
        district: "Faridabad",
        village: "Faridabad",
        isVerified: true,
        type: "Government",
        consultationFee: 600,
        contact: "0129-2811234",
        bio: "A 2,600-bed multi-specialty hospital providing world-class infrastructure and advanced medical care.",
        notableDoctors: [
            { name: "Dr. Sanjeev Singh", role: "Medical Director" },
            { name: "Dr. Prem Nair", role: "Gastroenterology" }
        ]
    },
    {
        id: "pvt-13",
        name: "KIMS Hospital Hyderabad",
        specialization: "Multi-specialty",
        hospitalName: "Krishna Institute of Medical Sciences",
        hospitalAddress: "1-8-31/1, Minister Road, Secunderabad - 500003",
        lat: 17.4340,
        lng: 78.4984,
        state: "Telangana",
        district: "Hyderabad",
        village: "Hyderabad",
        isVerified: true,
        type: "Government",
        consultationFee: 750,
        contact: "040-44885000",
        bio: "One of the largest corporate healthcare groups in AP and Telangana providing quaternary care.",
        notableDoctors: [
            { name: "Dr. Bhaskar Rao", role: "Cardiothoracic Surgery" },
            { name: "Dr. B. Abhinay", role: "CEO" }
        ]
    },
    {
        id: "pvt-14",
        name: "Aster CMI Hospital Bangalore",
        specialization: "Multi-specialty",
        hospitalName: "Aster CMI Hospital",
        hospitalAddress: "43/2, New Airport Road, NH-7, Sahakara Nagar, Bengaluru - 560092",
        lat: 13.0599,
        lng: 77.5914,
        state: "Karnataka",
        district: "Bangalore Urban",
        village: "Koramangala",
        isVerified: true,
        type: "Government",
        consultationFee: 850,
        contact: "080-43420100",
        bio: "A luxury multi-specialty hospital with state-of-the-art facilities and a focused patient care approach.",
        notableDoctors: [
            { name: "Dr. Nitish Shetty", role: "CEO" },
            { name: "Dr. Rajiv Lochan", role: "Liver Transplant" }
        ]
    },
    {
        id: "pvt-15",
        name: "Wockhardt Hospital Mumbai",
        specialization: "Cardiology",
        hospitalName: "Wockhardt Hospitals",
        hospitalAddress: "1877, Dr Anand Rao Nair Marg, Mumbai Central, Mumbai - 400011",
        lat: 18.9714,
        lng: 72.8199,
        state: "Maharashtra",
        district: "Mumbai",
        village: "Colaba",
        isVerified: true,
        type: "Government",
        consultationFee: 1100,
        contact: "022-61784444",
        bio: "A center of excellence in cardiac care providing comprehensive cardiovascular treatment and surgeries.",
        notableDoctors: [
            { name: "Dr. Clive Fernandes", role: "Group Hospital Operations" },
            { name: "Dr. Suresh Joshi", role: "Cardiac Surgery" }
        ]
    }
];
