const fs = require('fs');
const path = require('path');

const content = `# Replace the placeholder values with your actual Firebase project credentials.
# You can find these in your Firebase project settings.

NEXT_PUBLIC_FIREBASE_API_KEY="REPLACE_WITH_YOUR_KEY"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="REPLACE_WITH_YOUR_KEY"
NEXT_PUBLIC_FIREBASE_PROJECT_ID="REPLACE_WITH_YOUR_KEY"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="REPLACE_WITH_YOUR_KEY"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="REPLACE_WITH_YOUR_KEY"
NEXT_PUBLIC_FIREBASE_APP_ID="REPLACE_WITH_YOUR_KEY"
GEMINI_API_KEY="REPLACE_WITH_YOUR_KEY"
NEXT_PUBLIC_FIREBASE_GOOGLE_MAPS_API_KEY="REPLACE_WITH_YOUR_KEY"

NEXT_PUBLIC_SUPABASE_URL="REPLACE_WITH_YOUR_KEY"
NEXT_PUBLIC_SUPABASE_ANON_KEY="REPLACE_WITH_YOUR_KEY"
NEXT_PUBLIC_CRYPTO_SECRET=REPLACE_WITH_YOUR_KEY

FIREBASE_CLIENT_EMAIL="REPLACE_WITH_YOUR_KEY"
FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\\nREPLACE_WITH_YOUR_KEY\\n-----END PRIVATE KEY-----\\n"
`;

fs.writeFileSync(path.join(process.cwd(), '.env.local'), content);
console.log('.env.local has been updated successfully.');
